### 상위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CU000001",
  "category_name":"가전",
  "category_desc":"가전 전체 입니다.",
  "category_level":"U",
  "category_order":1,
  "upper_category_id":""
}


### 상위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CU000002",
  "category_name":"의류",
  "category_desc":"의류카테고리 입니다.",
  "category_level":"U",
  "category_order":2,
  "upper_category_id":""
}

### 가전 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000001",
  "category_name":"냉장고",
  "category_desc":"냉장고 카테고리 입니다.",
  "category_level":"L",
  "category_order":1,
  "upper_category_id":"CU000001"
}

### 가전 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000002",
  "category_name":"티비",
  "category_desc":"티비 카테고리 입니다.",
  "category_level":"L",
  "category_order":2,
  "upper_category_id":"CU000001"
}

### 가전 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000003",
  "category_name":"에어컨",
  "category_desc":"에어컨 카테고리 입니다.",
  "category_level":"L",
  "category_order":3,
  "upper_category_id":"CU000001"
}

### 의류 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000004",
  "category_name":"상의",
  "category_desc":"상의 카테고리 입니다.",
  "category_level":"L",
  "category_order":1,
  "upper_category_id":"CU000002"
}

### 의류 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000005",
  "category_name":"하의",
  "category_desc":"하의 카테고리 입니다.",
  "category_level":"L",
  "category_order":2,
  "upper_category_id":"CU000002"
}

### 의류 하위 카테고리 등록
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category_id":"CL000006",
  "category_name":"아우터",
  "category_desc":"아우터 카테고리 입니다.",
  "category_level":"L",
  "category_order":3,
  "upper_category_id":"CU000002"
}

### 카테고리 전체 조회
GET http://localhost:8080/api/v1/category
Content-Type: application/json

### 상위 카테고리 개별 조회
GET http://localhost:8080/api/v1/category/CU000001
Content-Type: application/json

### 카테고리 수정
PATCH http://localhost:8080/api/v1/category/CU000001
Content-Type: application/json

{
  "category_id": "CU000001",
  "upper_category_id": null,
  "category_name": "가전 변경 입니다.",
  "category_desc": "가전 변경 카테고리입니다.",
  "category_level": "U",
  "category_order": null,
  "low_category": []
}

### 카테고리 수정
PATCH http://localhost:8080/api/v1/category/CU000001
Content-Type: application/json

{
  "category_id": "CU000001",
  "upper_category_id": null,
  "category_name": "가전 변경 입니다.",
  "category_desc": "가전 변경 카테고리입니다.",
  "category_level": "U",
  "category_order": null,
  "low_category": []
}

### 카테고리 삭제
DELETE http://localhost:8080/api/v1/category/CL000003
Content-Type: application/json
